# Generated by Django 4.0.6 on 2022-07-12 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_allocated_team', to='users.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='team_members',
            field=models.ManyToManyField(help_text='Task assigned to users', to=settings.AUTH_USER_MODEL),
        ),
    ]
